name: publish
on:
  create:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        path-type: inherit
        install: rsync
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm install -g nw-gyp prebuildify node-gyp
    - run: powershell Install-WindowsFeature Net-Framework-Core
    - run: npm run test
    - run: ./make --build --build-cs --sign
      env:
        MSYS2_ARG_CONV_EXCL: "*"
        SIGNING_SERVER: ${{ secrets.SIGNING_SERVER }}
    - run: npm publish
      shell: cmd
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
