name: tests
on: [push]
jobs:
  tests:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        path-type: inherit
        install: rsync
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm install -g nw-gyp prebuildify node-gyp
    - run: powershell Install-WindowsFeature Net-Framework-Core
    - run: ./make.bat
    - run: npm run test



