name: tests
on: [push]
jobs:
  tests:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        path-type: inherit
        install: rsync
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm ls
    - run: npm install -g nw-gyp prebuildify node-gyp
    - run: powershell Install-WindowsFeature Net-Framework-Core
    - run: ./make --build --build-cs
      env:
        MSYS2_ARG_CONV_EXCL: "*"
    - run: npm run test



