name: tests
on: [push]

jobs:
  tests:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        path-type: inherit
        install: rsync
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm ls
    - run: npm install -g nw-gyp prebuildify node-gyp
    - name: Install .NET Framework 3.5
      shell: pwsh
      run: |
        if (-not (Get-WindowsOptionalFeature -Online -FeatureName Net-Framework-Core).State -eq 'Enabled') {
          Install-WindowsFeature Net-Framework-Core -Source D:\sources\sxs -LimitSource -All
        }
    - run: ./make --build --build-cs
      env:
        MSYS2_ARG_CONV_EXCL: "*"
    - run: npm run test



